# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2116cee78d57c01586197f903da393276bd161d288c9c83c4e7a9bb24c0f6b7a3c1e63f743e6ed7f3d85de6dce75e7826e86058496691dff670dbc3f32749197

test:
  secret_key_base: f8a2368f2da9f82c401594de40ac84037148b4ee5811cf72a7e2e959d4ab4147dfa0dc8c1ec2fa1853a417fa7138e249976e46f335e5ba37d89a0497b40c9694

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
